a=input()
j=input()
s=float(a) + float(j)
n=float(a)
w=int(j)
m=float(a) * float(j)
e=float(a) / float(j)
f=float(a) // float(j)
g=float(a) ** float(j)
h=float(a) % float(j)
print(s)
print(f'{n}{w}')
print(m)
print(f'{n}'*w)
print(e)
print(f)
print(g)
print(h)

